select * from sysobjects where name like '%TEMPLATE%'

select * from EMX_TEMPLATE_LISTA_FLEXFIELD
where EMX_TEMPLATE_LISTA_FLEXFIELD_DESCRICAO = 'Lista VIP Uberlândia'

Lista VIP Uberlândia 38

select * from EMX_TEMPLATE_RESPOSTA_ITEM
select * from EMX_TEMPLATE_LISTA_FLEXFIELD_ITEM_FILHO


select EMX_TEMPLATE_LISTA_FLEXFIELD_ITEM_ID, EMX_TEMPLATE_LISTA_FLEXFIELD_ITEM_DESCRICAO
from EMX_TEMPLATE_LISTA_FLEXFIELD_ITEM
where EMX_TEMPLATE_LISTA_FLEXFIELD_ID = 38