if object_id('spINotaFiscalUsoConsumo') is not null
	drop procedure dbo.spINotaFiscalUsoConsumo
go
CREATE PROCEDURE dbo.spINotaFiscalUsoConsumo
	@CodigoEmpresa numeric(4) ,
	@CodigoLocal numeric(4) ,
	@CodigoCliFor numeric(14) ,
	@Documento numeric(12) ,
	@DataLancamentoNFUsoCo datetime ,
	@DataEmissaoNFUsoCo datetime ,
	@Especie char(3) ,
	@Serie char(3) ,
	@ServicoMaterialConsumo char(1) = 'F',
	@ValorBruto money ,
	@IrrfFederal money = Null,
	@IrrfEstadual money = Null,
	@ValorLiquido money ,
	@ValorBaseICMSCapaNFUsoCo money = 0,
	@PercBaseICMSCapaNFUsoCo numeric(4,2) = 0,
	@ValorICMSCapaNFUsoCo money = 0,
	@ValorICMSSDirCapaNFUsoCo money = 0,
	@ValorBaseIPICapaNFUsoCo money = 0,
	@ValorSeguridadeCapaNFUsoCo money = 0,
	@CodigoNaturezaOperacao numeric(6) ,
	@CaracteristicaTipoDocto char(2) ,
	@CodigoTipoDocumento numeric(2) ,
	@CentroCusto numeric(8) ,
	@CodigoPlanoPagamento char(4) = Null,
	@CodigoTipoPagamento numeric(2) ,
	@CodigoModeloNotaFiscal numeric(2) ,
	@ValorBasePISCapaNFUsoCo money = 0,
	@ValorPISCapaNFUsoCo money = 0,
	@PercPISCapaNFUsoCo numeric(4,2) = 0,
	@ValorBaseCOFINSCapaNFUsoCo money = 0,
	@ValorCOFINSCapaNFUsoCo money = 0,
	@PercCOFINSCapaNFUsoCo numeric(4,2) = 0,
	@ValorContribSocCapaNFUsoCo money = 0,
	@ValorPIS135CapaNFUsoCo money = 0,
	@ValorCOFINS135CapaNFUsoCo money = 0,
	@ValorBaseISSCapaNFUsoCo money = 0,
	@PercISSCapaNFUsoCo numeric(4,2) = 0,
	@ValorISSCapaNFUsoCo money = 0,
	@NumeroChassisCV char(21) = Null,
	@AtividadeServicoNFUsoCo char(10) = Null,
	@ValorDescontoNFUsoCo money = 0,
	@DataVenctoNFUsoCo datetime = Null,
	@NumeroEncomenda numeric(6) = null,
	@ChaveNFE varchar(44) = '',
	@CodigoTipoAquisicao numeric(4) = null, 
	@NaturezaCreditoPisCofins varchar(2) = '',
	@TipoFrete dtInteiro01 = null,
	@ValorFrete dtValorMonetario = null,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
	@CodigoTipoReceitaDespesa varchar(20) = null
AS 
INSERT tbNotaFiscalUsoConsumo (
	CodigoEmpresa,
	CodigoLocal,
	CodigoCliFor,
	Documento,
	DataLancamentoNFUsoCo,
	DataEmissaoNFUsoCo,
	Especie,
	Serie,
	ServicoMaterialConsumo,
	ValorBruto,
	IrrfFederal,
	IrrfEstadual,
	ValorLiquido,
	ValorBaseICMSCapaNFUsoCo,
	PercBaseICMSCapaNFUsoCo,
	ValorICMSCapaNFUsoCo,
	ValorICMSSDirCapaNFUsoCo,
	ValorBaseIPICapaNFUsoCo,
	ValorSeguridadeCapaNFUsoCo,
	CodigoNaturezaOperacao,
	CaracteristicaTipoDocto,
	CodigoTipoDocumento,
	CentroCusto,
	CodigoPlanoPagamento,
	CodigoTipoPagamento,
	CodigoModeloNotaFiscal,
	ValorBasePISCapaNFUsoCo,
	ValorPISCapaNFUsoCo,
	PercPISCapaNFUsoCo,
	ValorBaseCOFINSCapaNFUsoCo,
	ValorCOFINSCapaNFUsoCo,
	PercCOFINSCapaNFUsoCo,
	ValorContribSocCapaNFUsoCo,
	ValorPIS135CapaNFUsoCo,
	ValorCOFINS135CapaNFUsoCo,
	ValorBaseISSCapaNFUsoCo,
	PercISSCapaNFUsoCo,
	ValorISSCapaNFUsoCo,
	NumeroChassisCV,
	AtividadeServicoNFUsoCo,
	ValorDescontoNFUsoCo,
	DataVenctoNFUsoCo,
	NumeroEncomenda,
	ChaveNFE,
	CodigoTipoAquisicao, 
	NaturezaCreditoPisCofins,
	TipoFrete,
	ValorFrete,
	MunicipioOrigem,
	MunicipioDestino,
	CodigoTipoReceitaDespesa
) VALUES (
	@CodigoEmpresa,
	@CodigoLocal,
	@CodigoCliFor,
	@Documento,
	@DataLancamentoNFUsoCo,
	@DataEmissaoNFUsoCo,
	@Especie,
	@Serie,
	@ServicoMaterialConsumo,
	@ValorBruto,
	@IrrfFederal,
	@IrrfEstadual,
	@ValorLiquido,
	@ValorBaseICMSCapaNFUsoCo,
	@PercBaseICMSCapaNFUsoCo,
	@ValorICMSCapaNFUsoCo,
	@ValorICMSSDirCapaNFUsoCo,
	@ValorBaseIPICapaNFUsoCo,
	@ValorSeguridadeCapaNFUsoCo,
	@CodigoNaturezaOperacao,
	@CaracteristicaTipoDocto,
	@CodigoTipoDocumento,
	@CentroCusto,
	@CodigoPlanoPagamento,
	@CodigoTipoPagamento,
	@CodigoModeloNotaFiscal,
	@ValorBasePISCapaNFUsoCo,
	@ValorPISCapaNFUsoCo,
	@PercPISCapaNFUsoCo,
	@ValorBaseCOFINSCapaNFUsoCo,
	@ValorCOFINSCapaNFUsoCo,
	@PercCOFINSCapaNFUsoCo,
	@ValorContribSocCapaNFUsoCo,
	@ValorPIS135CapaNFUsoCo,
	@ValorCOFINS135CapaNFUsoCo,
	@ValorBaseISSCapaNFUsoCo,
	@PercISSCapaNFUsoCo,
	@ValorISSCapaNFUsoCo,
	@NumeroChassisCV,
	@AtividadeServicoNFUsoCo,
	@ValorDescontoNFUsoCo,
	@DataVenctoNFUsoCo,
	@NumeroEncomenda,
	@ChaveNFE,
	@CodigoTipoAquisicao, 
	@NaturezaCreditoPisCofins,
	@TipoFrete,
	@ValorFrete,
	@MunicipioOrigem,
	@MunicipioDestino,
	@CodigoTipoReceitaDespesa	)
go
grant execute on dbo.spANFDocumento to SQLUsers
go
if object_id('spANotaFiscalUsoConsumo') is not null
	drop procedure dbo.spANotaFiscalUsoConsumo
go
CREATE PROCEDURE dbo.spANotaFiscalUsoConsumo
	@CodigoEmpresa numeric(4) ,
	@CodigoLocal numeric(4) ,
	@CodigoCliFor numeric(14) ,
	@Documento numeric(12) ,
	@DataLancamentoNFUsoCo datetime ,
	@DataEmissaoNFUsoCo datetime ,
	@Especie char(3) ,
	@Serie char(3) ,
	@ServicoMaterialConsumo char(1) = 'F',
	@ValorBruto money ,
	@IrrfFederal money = Null,
	@IrrfEstadual money = Null,
	@ValorLiquido money ,
	@ValorBaseICMSCapaNFUsoCo money = 0,
	@PercBaseICMSCapaNFUsoCo numeric(4,2) = 0,
	@ValorICMSCapaNFUsoCo money = 0,
	@ValorICMSSDirCapaNFUsoCo money = 0,
	@ValorBaseIPICapaNFUsoCo money = 0,
	@ValorSeguridadeCapaNFUsoCo money = 0,
	@CodigoNaturezaOperacao numeric(6) ,
	@CaracteristicaTipoDocto char(2) ,
	@CodigoTipoDocumento numeric(2) ,
	@CentroCusto numeric(8) ,
	@CodigoPlanoPagamento char(4) = Null,
	@CodigoTipoPagamento numeric(2) ,
	@CodigoModeloNotaFiscal numeric(2) ,
	@ValorBasePISCapaNFUsoCo money = 0,
	@ValorPISCapaNFUsoCo money = 0,
	@PercPISCapaNFUsoCo numeric(4,2) = 0,
	@ValorBaseCOFINSCapaNFUsoCo money = 0,
	@ValorCOFINSCapaNFUsoCo money = 0,
	@PercCOFINSCapaNFUsoCo numeric(4,2) = 0,
	@ValorContribSocCapaNFUsoCo money = 0,
	@ValorPIS135CapaNFUsoCo money = 0,
	@ValorCOFINS135CapaNFUsoCo money = 0,
	@ValorBaseISSCapaNFUsoCo money = 0,
	@PercISSCapaNFUsoCo numeric(4,2) = 0,
	@ValorISSCapaNFUsoCo money = 0,
	@NumeroChassisCV char(21) = Null,
	@AtividadeServicoNFUsoCo char(10) = Null,
	@ValorDescontoNFUsoCo money = 0,
	@DataVenctoNFUsoCo datetime = Null,
	@NumeroEncomenda numeric(6) = null,
	@ChaveNFE varchar(44) = '',
	@CodigoTipoAquisicao numeric(4) = null, 
	@NaturezaCreditoPisCofins varchar(2) = '',
	@TipoFrete dtInteiro01 = null,
	@ValorFrete dtValorMonetario = null,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
	@CodigoTipoReceitaDespesa varchar(20) = null
AS 
UPDATE tbNotaFiscalUsoConsumo
SET
	DataLancamentoNFUsoCo = @DataLancamentoNFUsoCo,
	DataEmissaoNFUsoCo = @DataEmissaoNFUsoCo,
	Especie = @Especie,
	Serie = @Serie,
	ServicoMaterialConsumo = @ServicoMaterialConsumo,
	ValorBruto = @ValorBruto,
	IrrfFederal = @IrrfFederal,
	IrrfEstadual = @IrrfEstadual,
	ValorLiquido = @ValorLiquido,
	ValorBaseICMSCapaNFUsoCo = @ValorBaseICMSCapaNFUsoCo,
	PercBaseICMSCapaNFUsoCo = @PercBaseICMSCapaNFUsoCo,
	ValorICMSCapaNFUsoCo = @ValorICMSCapaNFUsoCo,
	ValorICMSSDirCapaNFUsoCo = @ValorICMSSDirCapaNFUsoCo,
	ValorBaseIPICapaNFUsoCo = @ValorBaseIPICapaNFUsoCo,
	ValorSeguridadeCapaNFUsoCo = @ValorSeguridadeCapaNFUsoCo,
	CodigoNaturezaOperacao = @CodigoNaturezaOperacao,
	CaracteristicaTipoDocto = @CaracteristicaTipoDocto,
	CodigoTipoDocumento = @CodigoTipoDocumento,
	CentroCusto = @CentroCusto,
	CodigoPlanoPagamento = @CodigoPlanoPagamento,
	CodigoTipoPagamento = @CodigoTipoPagamento,
	CodigoModeloNotaFiscal = @CodigoModeloNotaFiscal,
	ValorBasePISCapaNFUsoCo = @ValorBasePISCapaNFUsoCo,
	ValorPISCapaNFUsoCo = @ValorPISCapaNFUsoCo,
	PercPISCapaNFUsoCo = @PercPISCapaNFUsoCo,
	ValorBaseCOFINSCapaNFUsoCo = @ValorBaseCOFINSCapaNFUsoCo,
	ValorCOFINSCapaNFUsoCo = @ValorCOFINSCapaNFUsoCo,
	PercCOFINSCapaNFUsoCo = @PercCOFINSCapaNFUsoCo,
	ValorContribSocCapaNFUsoCo = @ValorContribSocCapaNFUsoCo,
	ValorPIS135CapaNFUsoCo = @ValorPIS135CapaNFUsoCo,
	ValorCOFINS135CapaNFUsoCo = @ValorCOFINS135CapaNFUsoCo,
	ValorBaseISSCapaNFUsoCo = @ValorBaseISSCapaNFUsoCo,
	PercISSCapaNFUsoCo = @PercISSCapaNFUsoCo,
	ValorISSCapaNFUsoCo = @ValorISSCapaNFUsoCo,
	NumeroChassisCV = @NumeroChassisCV,
	AtividadeServicoNFUsoCo = @AtividadeServicoNFUsoCo,
	ValorDescontoNFUsoCo = @ValorDescontoNFUsoCo,
	DataVenctoNFUsoCo = @DataVenctoNFUsoCo,
	NumeroEncomenda = @NumeroEncomenda,
	ChaveNFE = @ChaveNFE,
	CodigoTipoAquisicao = @CodigoTipoAquisicao, 
	NaturezaCreditoPisCofins = @NaturezaCreditoPisCofins,
	TipoFrete = @TipoFrete,
	ValorFrete = @ValorFrete,
	MunicipioOrigem = @MunicipioOrigem,
	MunicipioDestino = @MunicipioDestino,
	CodigoTipoReceitaDespesa = @CodigoTipoReceitaDespesa
WHERE 
	CodigoEmpresa = @CodigoEmpresa AND
	CodigoLocal = @CodigoLocal AND
	CodigoCliFor = @CodigoCliFor AND
	Documento = @Documento
go
grant execute on dbo.spANotaFiscalUsoConsumo to SQLUsers
go
if object_id('spINotaDigitada') is not null
	drop procedure dbo.spINotaDigitada
go
CREATE PROCEDURE dbo.spINotaDigitada
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliFor numeric(14) ,
   @DocumentoNotaDigitada numeric(12) ,
   @EncerradoNotaDigitada char(1) = 'F',
   @EspecieNotaDigitada char(3) ,
   @SerieNotaDigitada char(4) ,
   @DataNotaDigitada datetime = Null,
   @DataEmissaoNotaDigitada datetime = Null,
   @StatusDocumentoNotaDigitada numeric(1) = 1,
   @ValorFreteInfNotaDigitada money = 0,
   @ValorSeguroInfNotaDigitada money = 0,
   @ValorDespesasInfNotaDigitada money = 0,
   @ValorCTRCInformadoNotaDigitad money = 0,
   @ValorEncFinProdInfNotaDigitad money = 0,
   @ValorEncFinServInfNotaDigitad money = 0,
   @ValorEncFinIsentoNotaDigitada money = 0,
   @ValorProdutosInfNotaDigitada money ,
   @ValorServInformadoNotaDigitad money = 0,
   @ValorIPIInformadoNotaDigitada money = 0,
   @ValorDescProdInfNotaDigitada money = 0,
   @ValorDescServInfNotaDigitada money = 0,
   @ValorDocumentoInfNotaDigitada money ,
   @ValorICMSInformadoNotaDigitad money = 0,
   @ValorDuplicataApuNotaDigitada money = 0,
   @ValorEncFinProdApuNotaDigitad money = 0,
   @ValorEncFinServApuNotaDigitad money = 0,
   @ValorProdutoApuNotaDigitada money = 0,
   @ValorServApuradoNotaDigitada money = 0,
   @ValorIPIApuradoNotaDigitada money = 0,
   @ValorDescProdApuNotaDigitada money = 0,
   @ValorDocumentoApuNotaDigitada money = 0,
   @ValorICMSApuradoNotaDigitada money = 0,
   @PercentualICMSNotaDigitada numeric(4,2) = 0,
   @PrecoRepAtualizadoNotaDigitad char(1) = 'F',
   @CPAtualizadoNotaDigitada char(1) = 'F',
   @LFAtualizadoNotaDigitada char(1) = 'F',
   @EstoqueAtualizadoNotaDigitada char(1) = 'F',
   @CGAtualizadaNotaDigitada char(1) = 'F',
   @ValorICMSRateioNotaDigitada money = 0,
   @BaseICMS1NotaDigitada money = 0,
   @BaseICMS2NotaDigitada money = 0,
   @BaseICMS3NotaDigitada money = 0,
   @BaseIPI1NotaDigitada money = 0,
   @BaseIPI2NotaDigitada money = 0,
   @BaseIPI3NotaDigitada money = 0,
   @ICMSRetidoFonteApuNotaDigitad money = 0,
   @ICMSRetidoFonteInfNotaDigitad money = 0,
   @ICMSOriginalNotaDigitada money = 0,
   @ICMSSemDireitoCredNotaDigitad money = 0,
   @AtualizaPrecoVenda char(1) = 'F',
   @DataValidadePrecoVenda datetime = Null,
   @NumeroControleNotaDigitada numeric(8) = Null,
   @NumeroLoteGerado int = Null,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoTipoDocumento numeric(2) ,
   @CodigoPlanoPagamento char(4) = Null,
   @CentroCusto numeric(8) ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CodigoNaturezaOperacaoIN428 numeric(6) = Null,
   @ICMSSubstTribInfNotaDigitada money = 0,
   @ICMSSubstTribApuNotaDigitada money = 0,
   @BaseSubstTribInfNotaDigitada money = 0,
   @BaseSubstTribApuNotaDigitada money = 0,
   @ValorPISNotaDigitada money = 0,
   @ValorCOFINSNotaDigitada money = 0,
   @PercDecreto43708MG numeric(4,2) = 0,
   @IntegraColetor char(1) = 'F',
   @ValorTotalConsumo money = 0,
   @CodigoTipoPagamento numeric(2) = null,
   @CodigoNaturezaOperacaoConsumo numeric(6) = null,
   @CodigoModeloNotaFiscal numeric(2),
   @ChaveAcessoNFe char(44) = '',
   @AtualizaKitNotaDigitada char(1) = 'F',
   @TipoFrete dtInteiro01 = 9,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS
IF @DataNotaDigitada is Null
BEGIN
   SELECT @DataNotaDigitada = getdate()
END
IF @DataEmissaoNotaDigitada is Null
BEGIN
   SELECT @DataEmissaoNotaDigitada = getdate()
END
IF @CodigoTipoPagamento = 0
BEGIN
	SELECT	@CodigoTipoPagamento = MIN(CodigoTipoPagamento) 
	FROM	tbTipoPagamento
	WHERE	CodigoEmpresa	= @CodigoEmpresa
END
INSERT tbNotaDigitada
   (CodigoEmpresa,
   CodigoLocal,
   CodigoCliFor,
   DocumentoNotaDigitada,
   EncerradoNotaDigitada,
   EspecieNotaDigitada,
   SerieNotaDigitada,
   DataNotaDigitada,
   DataEmissaoNotaDigitada,
   StatusDocumentoNotaDigitada,
   ValorFreteInfNotaDigitada,
   ValorSeguroInfNotaDigitada,
   ValorDespesasInfNotaDigitada,
   ValorCTRCInformadoNotaDigitada,
   ValorEncFinProdInfNotaDigitada,
   ValorEncFinServInfNotaDigitada,
   ValorEncFinIsentoNotaDigitada,
   ValorProdutosInfNotaDigitada,
   ValorServInformadoNotaDigitada,
   ValorIPIInformadoNotaDigitada,
   ValorDescProdInfNotaDigitada,
   ValorDescServInfNotaDigitada,
   ValorDocumentoInfNotaDigitada,
   ValorICMSInformadoNotaDigitada,
   ValorDuplicataApuNotaDigitada,
   ValorEncFinProdApuNotaDigitada,
   ValorEncFinServApuNotaDigitada,
   ValorProdutoApuNotaDigitada,
   ValorServApuradoNotaDigitada,
   ValorIPIApuradoNotaDigitada,
   ValorDescProdApuNotaDigitada,
   ValorDocumentoApuNotaDigitada,
   ValorICMSApuradoNotaDigitada,
   PercentualICMSNotaDigitada,
   PrecoRepAtualizadoNotaDigitada,
   CPAtualizadoNotaDigitada,
   LFAtualizadoNotaDigitada,
   EstoqueAtualizadoNotaDigitada,
   CGAtualizadaNotaDigitada,
   ValorICMSRateioNotaDigitada,
   BaseICMS1NotaDigitada,
   BaseICMS2NotaDigitada,
   BaseICMS3NotaDigitada,
   BaseIPI1NotaDigitada,
   BaseIPI2NotaDigitada,
   BaseIPI3NotaDigitada,
   ICMSRetidoFonteApuNotaDigitada,
   ICMSRetidoFonteInfNotaDigitada,
   ICMSOriginalNotaDigitada,
   ICMSSemDireitoCredNotaDigitada,
   AtualizaPrecoVenda,
   DataValidadePrecoVenda,
   NumeroControleNotaDigitada,
   NumeroLoteGerado,
   CaracteristicaTipoDocto,
   CodigoTipoDocumento,
   CodigoPlanoPagamento,
   CentroCusto,
   CodigoNaturezaOperacao,
   CodigoNaturezaOperacaoIN428,
   ICMSSubstTribInfNotaDigitada,
   ICMSSubstTribApuNotaDigitada,
   BaseSubstTribInfNotaDigitada,
   BaseSubstTribApuNotaDigitada,
   ValorPISNotaDigitada,
   ValorCOFINSNotaDigitada,
   PercDecreto43708MG,
   IntegraColetor,
   ValorTotalConsumo,
   CodigoTipoPagamento,
   CodigoNaturezaOperacaoConsumo,
   CodigoModeloNotaFiscal,
   ChaveAcessoNFe,
   AtualizaKitNotaDigitada,
   TipoFrete,
	MunicipioOrigem,
	MunicipioDestino,
   CodigoTipoReceitaDespesa
) VALUES (
   @CodigoEmpresa,
   @CodigoLocal,
   @CodigoCliFor,
   @DocumentoNotaDigitada,
   @EncerradoNotaDigitada,
   @EspecieNotaDigitada,
   @SerieNotaDigitada,
   @DataNotaDigitada,
   @DataEmissaoNotaDigitada,
   @StatusDocumentoNotaDigitada,
   @ValorFreteInfNotaDigitada,
   @ValorSeguroInfNotaDigitada,
   @ValorDespesasInfNotaDigitada,
   @ValorCTRCInformadoNotaDigitad,
   @ValorEncFinProdInfNotaDigitad,
   @ValorEncFinServInfNotaDigitad,
   @ValorEncFinIsentoNotaDigitada,
   @ValorProdutosInfNotaDigitada,
   @ValorServInformadoNotaDigitad,
   @ValorIPIInformadoNotaDigitada,
   @ValorDescProdInfNotaDigitada,
   @ValorDescServInfNotaDigitada,
   @ValorDocumentoInfNotaDigitada,
   @ValorICMSInformadoNotaDigitad,
   @ValorDuplicataApuNotaDigitada,
   @ValorEncFinProdApuNotaDigitad,
   @ValorEncFinServApuNotaDigitad,
   @ValorProdutoApuNotaDigitada,
   @ValorServApuradoNotaDigitada,
   @ValorIPIApuradoNotaDigitada,
   @ValorDescProdApuNotaDigitada,
   @ValorDocumentoApuNotaDigitada,
   @ValorICMSApuradoNotaDigitada,
   @PercentualICMSNotaDigitada,
   @PrecoRepAtualizadoNotaDigitad,
   @CPAtualizadoNotaDigitada,
   @LFAtualizadoNotaDigitada,
   @EstoqueAtualizadoNotaDigitada,
   @CGAtualizadaNotaDigitada,
   @ValorICMSRateioNotaDigitada,
   @BaseICMS1NotaDigitada,
   @BaseICMS2NotaDigitada,
   @BaseICMS3NotaDigitada,
   @BaseIPI1NotaDigitada,
   @BaseIPI2NotaDigitada,
   @BaseIPI3NotaDigitada,
   @ICMSRetidoFonteApuNotaDigitad,
   @ICMSRetidoFonteInfNotaDigitad,
   @ICMSOriginalNotaDigitada,
   @ICMSSemDireitoCredNotaDigitad,
   @AtualizaPrecoVenda,
   @DataValidadePrecoVenda,
   @NumeroControleNotaDigitada,
   @NumeroLoteGerado,
   @CaracteristicaTipoDocto,
   @CodigoTipoDocumento,
   @CodigoPlanoPagamento,
   @CentroCusto,
   @CodigoNaturezaOperacao,
   @CodigoNaturezaOperacaoIN428,
   @ICMSSubstTribInfNotaDigitada,
   @ICMSSubstTribApuNotaDigitada,
   @BaseSubstTribInfNotaDigitada,
   @BaseSubstTribApuNotaDigitada,
   @ValorPISNotaDigitada,
   @ValorCOFINSNotaDigitada,
   @PercDecreto43708MG,
   @IntegraColetor,
   @ValorTotalConsumo,
   @CodigoTipoPagamento,
   @CodigoNaturezaOperacaoConsumo,
   @CodigoModeloNotaFiscal,
   @ChaveAcessoNFe,
   @AtualizaKitNotaDigitada,
   @TipoFrete,
	@MunicipioOrigem,
	@MunicipioDestino,
   @CodigoTipoReceitaDespesa
   )
go
grant execute on dbo.spINotaDigitada to SQLUsers
go
if object_id('spANotaDigitada') is not null
	drop procedure dbo.spANotaDigitada
go
CREATE PROCEDURE dbo.spANotaDigitada
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliFor numeric(14) ,
   @DocumentoNotaDigitada numeric(12) ,
   @EncerradoNotaDigitada char(1) = 'F',
   @EspecieNotaDigitada char(3) ,
   @SerieNotaDigitada char(4) ,
   @DataNotaDigitada datetime = Null,
   @DataEmissaoNotaDigitada datetime = Null,
   @StatusDocumentoNotaDigitada numeric(1) = 1,
   @ValorFreteInfNotaDigitada money = 0,
   @ValorSeguroInfNotaDigitada money = 0,
   @ValorDespesasInfNotaDigitada money = 0,
   @ValorCTRCInformadoNotaDigitad money = 0,
   @ValorEncFinProdInfNotaDigitad money = 0,
   @ValorEncFinServInfNotaDigitad money = 0,
   @ValorEncFinIsentoNotaDigitada money = 0,
   @ValorProdutosInfNotaDigitada money ,
   @ValorServInformadoNotaDigitad money = 0,
   @ValorIPIInformadoNotaDigitada money = 0,
   @ValorDescProdInfNotaDigitada money = 0,
   @ValorDescServInfNotaDigitada money = 0,
   @ValorDocumentoInfNotaDigitada money ,
   @ValorICMSInformadoNotaDigitad money = 0,
   @ValorDuplicataApuNotaDigitada money = 0,
   @ValorEncFinProdApuNotaDigitad money = 0,
   @ValorEncFinServApuNotaDigitad money = 0,
   @ValorProdutoApuNotaDigitada money = 0,
   @ValorServApuradoNotaDigitada money = 0,
   @ValorIPIApuradoNotaDigitada money = 0,
   @ValorDescProdApuNotaDigitada money = 0,
   @ValorDocumentoApuNotaDigitada money = 0,
   @ValorICMSApuradoNotaDigitada money = 0,
   @PercentualICMSNotaDigitada numeric(4,2) = 0,
   @PrecoRepAtualizadoNotaDigitad char(1) = 'F',
   @CPAtualizadoNotaDigitada char(1) = 'F',
   @LFAtualizadoNotaDigitada char(1) = 'F',
   @EstoqueAtualizadoNotaDigitada char(1) = 'F',
   @CGAtualizadaNotaDigitada char(1) = 'F',
   @ValorICMSRateioNotaDigitada money = 0,
   @BaseICMS1NotaDigitada money = 0,
   @BaseICMS2NotaDigitada money = 0,
   @BaseICMS3NotaDigitada money = 0,
   @BaseIPI1NotaDigitada money = 0,
   @BaseIPI2NotaDigitada money = 0,
   @BaseIPI3NotaDigitada money = 0,
   @ICMSRetidoFonteApuNotaDigitad money = 0,
   @ICMSRetidoFonteInfNotaDigitad money = 0,
   @ICMSOriginalNotaDigitada money = 0,
   @ICMSSemDireitoCredNotaDigitad money = 0,
   @AtualizaPrecoVenda char(1) = 'F',
   @DataValidadePrecoVenda datetime = Null,
   @NumeroControleNotaDigitada numeric(8) = Null,
   @NumeroLoteGerado int = Null,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoTipoDocumento numeric(2) ,
   @CodigoPlanoPagamento char(4) = Null,
   @CentroCusto numeric(8) ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CodigoNaturezaOperacaoIN428 numeric(6) = Null,
   @ICMSSubstTribInfNotaDigitada money = 0,
   @ICMSSubstTribApuNotaDigitada money = 0,
   @BaseSubstTribInfNotaDigitada money = 0,
   @BaseSubstTribApuNotaDigitada money = 0,
   @ValorPISNotaDigitada money = 0,
   @ValorCOFINSNotaDigitada money = 0,
   @PercDecreto43708MG numeric(4,2) = 0,
   @IntegraColetor char(1) = 'F',
   @ValorTotalConsumo money = 0,
   @CodigoTipoPagamento numeric(2) = null,
   @CodigoNaturezaOperacaoConsumo numeric(6) = null,
   @CodigoModeloNotaFiscal numeric(2),
   @ChaveAcessoNFe char(44) = '',
   @AtualizaKitNotaDigitada char(1) = 'F',
   @TipoFrete dtInteiro01 = null,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS 
UPDATE tbNotaDigitada
SET
   EncerradoNotaDigitada = @EncerradoNotaDigitada,
   EspecieNotaDigitada = @EspecieNotaDigitada,
   SerieNotaDigitada = @SerieNotaDigitada,
   DataNotaDigitada = @DataNotaDigitada,
   DataEmissaoNotaDigitada = @DataEmissaoNotaDigitada,
   StatusDocumentoNotaDigitada = @StatusDocumentoNotaDigitada,
   ValorFreteInfNotaDigitada = @ValorFreteInfNotaDigitada,
   ValorSeguroInfNotaDigitada = @ValorSeguroInfNotaDigitada,
   ValorDespesasInfNotaDigitada = @ValorDespesasInfNotaDigitada,
   ValorCTRCInformadoNotaDigitada = @ValorCTRCInformadoNotaDigitad,
   ValorEncFinProdInfNotaDigitada = @ValorEncFinProdInfNotaDigitad,
   ValorEncFinServInfNotaDigitada = @ValorEncFinServInfNotaDigitad,
   ValorEncFinIsentoNotaDigitada = @ValorEncFinIsentoNotaDigitada,
   ValorProdutosInfNotaDigitada = @ValorProdutosInfNotaDigitada,
   ValorServInformadoNotaDigitada = @ValorServInformadoNotaDigitad,
   ValorIPIInformadoNotaDigitada = @ValorIPIInformadoNotaDigitada,
   ValorDescProdInfNotaDigitada = @ValorDescProdInfNotaDigitada,
   ValorDescServInfNotaDigitada = @ValorDescServInfNotaDigitada,
   ValorDocumentoInfNotaDigitada = @ValorDocumentoInfNotaDigitada,
   ValorICMSInformadoNotaDigitada = @ValorICMSInformadoNotaDigitad,
   ValorDuplicataApuNotaDigitada = @ValorDuplicataApuNotaDigitada,
   ValorEncFinProdApuNotaDigitada = @ValorEncFinProdApuNotaDigitad,
   ValorEncFinServApuNotaDigitada = @ValorEncFinServApuNotaDigitad,
   ValorProdutoApuNotaDigitada = @ValorProdutoApuNotaDigitada,
   ValorServApuradoNotaDigitada = @ValorServApuradoNotaDigitada,
   ValorIPIApuradoNotaDigitada = @ValorIPIApuradoNotaDigitada,
   ValorDescProdApuNotaDigitada = @ValorDescProdApuNotaDigitada,
   ValorDocumentoApuNotaDigitada = @ValorDocumentoApuNotaDigitada,
   ValorICMSApuradoNotaDigitada = @ValorICMSApuradoNotaDigitada,
   PercentualICMSNotaDigitada = @PercentualICMSNotaDigitada,
   PrecoRepAtualizadoNotaDigitada = @PrecoRepAtualizadoNotaDigitad,
   CPAtualizadoNotaDigitada = @CPAtualizadoNotaDigitada,
   LFAtualizadoNotaDigitada = @LFAtualizadoNotaDigitada,
   EstoqueAtualizadoNotaDigitada = @EstoqueAtualizadoNotaDigitada,
   CGAtualizadaNotaDigitada = @CGAtualizadaNotaDigitada,
   ValorICMSRateioNotaDigitada = @ValorICMSRateioNotaDigitada,
   BaseICMS1NotaDigitada = @BaseICMS1NotaDigitada,
   BaseICMS2NotaDigitada = @BaseICMS2NotaDigitada,
   BaseICMS3NotaDigitada = @BaseICMS3NotaDigitada,
   BaseIPI1NotaDigitada = @BaseIPI1NotaDigitada,
   BaseIPI2NotaDigitada = @BaseIPI2NotaDigitada,
   BaseIPI3NotaDigitada = @BaseIPI3NotaDigitada,
   ICMSRetidoFonteApuNotaDigitada = @ICMSRetidoFonteApuNotaDigitad,
   ICMSRetidoFonteInfNotaDigitada = @ICMSRetidoFonteInfNotaDigitad,
   ICMSOriginalNotaDigitada = @ICMSOriginalNotaDigitada,
   ICMSSemDireitoCredNotaDigitada = @ICMSSemDireitoCredNotaDigitad,
   AtualizaPrecoVenda = @AtualizaPrecoVenda,
   DataValidadePrecoVenda = @DataValidadePrecoVenda,
   NumeroControleNotaDigitada = @NumeroControleNotaDigitada,
   NumeroLoteGerado = @NumeroLoteGerado,
   CaracteristicaTipoDocto = @CaracteristicaTipoDocto,
   CodigoTipoDocumento = @CodigoTipoDocumento,
   CodigoPlanoPagamento = @CodigoPlanoPagamento,
   CentroCusto = @CentroCusto,
   CodigoNaturezaOperacao = @CodigoNaturezaOperacao,
   CodigoNaturezaOperacaoIN428 = @CodigoNaturezaOperacaoIN428,
   ICMSSubstTribInfNotaDigitada = @ICMSSubstTribInfNotaDigitada,
   ICMSSubstTribApuNotaDigitada = @ICMSSubstTribApuNotaDigitada,
   BaseSubstTribInfNotaDigitada = @BaseSubstTribInfNotaDigitada,
   BaseSubstTribApuNotaDigitada = @BaseSubstTribApuNotaDigitada,
   ValorPISNotaDigitada = @ValorPISNotaDigitada,
   ValorCOFINSNotaDigitada = @ValorCOFINSNotaDigitada,
   PercDecreto43708MG = @PercDecreto43708MG,
   IntegraColetor = @IntegraColetor,
   ValorTotalConsumo = @ValorTotalConsumo,
   CodigoTipoPagamento = @CodigoTipoPagamento,
   CodigoNaturezaOperacaoConsumo = @CodigoNaturezaOperacaoConsumo,
   CodigoModeloNotaFiscal = @CodigoModeloNotaFiscal,
   ChaveAcessoNFe = @ChaveAcessoNFe,
   AtualizaKitNotaDigitada = @AtualizaKitNotaDigitada,
   TipoFrete = @TipoFrete,
	MunicipioOrigem = @MunicipioOrigem,
	MunicipioDestino = @MunicipioDestino,
   CodigoTipoReceitaDespesa = @CodigoTipoReceitaDespesa
WHERE 
   CodigoEmpresa = @CodigoEmpresa AND
   CodigoLocal = @CodigoLocal AND
   CodigoCliFor = @CodigoCliFor AND
   DocumentoNotaDigitada = @DocumentoNotaDigitada
go
grant execute on dbo.spANotaDigitada to SQLUsers
go
if object_id('spICTRCEntrada') is not null
	drop procedure dbo.spICTRCEntrada
go
CREATE PROCEDURE dbo.spICTRCEntrada
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliForTransp numeric(14) ,
   @NumeroCTRC numeric(9) ,
   @ValorCTRCEntrada money ,
   @SerieCTRC char(4) ,
   @EspecieCTRC char(3) ,
   @LoteCorretoCTRC char(1) = 'F',
   @ValorICMSCTRC money = 0,
   @ValorProdutosCTRC money ,
   @DataEntradaCTRC datetime ,
   @DataEmissaoCTRC datetime ,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoTipoDocumento numeric(2) ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CentroCusto numeric(8) ,
   @CodigoPlanoPagamento char(4) = Null,
   @ValorBaseICMSCTRC money = 0,
   @ValorBaseSubstTributaria money = 0,
   @ValorSubstTributaria money = 0,
   @CodigoTipoPagamento numeric(2),
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS 
INSERT tbCTRCEntrada
   (CodigoEmpresa,
   CodigoLocal,
   CodigoCliForTransp,
   NumeroCTRC,
   ValorCTRCEntrada,
   SerieCTRC,
   EspecieCTRC,
   LoteCorretoCTRC,
   ValorICMSCTRC,
   ValorProdutosCTRC,
   DataEntradaCTRC,
   DataEmissaoCTRC,
   CaracteristicaTipoDocto,
   CodigoTipoDocumento,
   CodigoNaturezaOperacao,
   CentroCusto,
   CodigoPlanoPagamento,
   ValorBaseICMSCTRC,
   ValorBaseSubstTributaria,
   ValorSubstTributaria,
   CodigoTipoPagamento,
	MunicipioOrigem,
	MunicipioDestino,
    CodigoTipoReceitaDespesa
) VALUES (
   @CodigoEmpresa,
   @CodigoLocal,
   @CodigoCliForTransp,
   @NumeroCTRC,
   @ValorCTRCEntrada,
   @SerieCTRC,
   @EspecieCTRC,
   @LoteCorretoCTRC,
   @ValorICMSCTRC,
   @ValorProdutosCTRC,
   @DataEntradaCTRC,
   @DataEmissaoCTRC,
   @CaracteristicaTipoDocto,
   @CodigoTipoDocumento,
   @CodigoNaturezaOperacao,
   @CentroCusto,
   @CodigoPlanoPagamento,
   @ValorBaseICMSCTRC,
   @ValorBaseSubstTributaria,
   @ValorSubstTributaria,
   @CodigoTipoPagamento,
	@MunicipioOrigem,
	@MunicipioDestino,
   @CodigoTipoReceitaDespesa
   )
go
grant execute on dbo.spICTRCEntrada to SQLUsers
go
if object_id('spACTRCEntrada') is not null
	drop procedure dbo.spACTRCEntrada
go
CREATE PROCEDURE dbo.spACTRCEntrada
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliForTransp numeric(14) ,
   @NumeroCTRC numeric(9) ,
   @ValorCTRCEntrada money ,
   @SerieCTRC char(4) ,
   @EspecieCTRC char(3) ,
   @LoteCorretoCTRC char(1) = 'F',
   @ValorICMSCTRC money = 0,
   @ValorProdutosCTRC money ,
   @DataEntradaCTRC datetime ,
   @DataEmissaoCTRC datetime ,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoTipoDocumento numeric(2) ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CentroCusto numeric(8) ,
   @CodigoPlanoPagamento char(4) = Null,
   @ValorBaseICMSCTRC money = 0,
   @ValorBaseSubstTributaria money = 0,
   @ValorSubstTributaria money = 0,
   @CodigoTipoPagamento numeric(2),
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS 
UPDATE tbCTRCEntrada
SET
   ValorCTRCEntrada = @ValorCTRCEntrada,
   SerieCTRC = @SerieCTRC,
   EspecieCTRC = @EspecieCTRC,
   LoteCorretoCTRC = @LoteCorretoCTRC,
   ValorICMSCTRC = @ValorICMSCTRC,
   ValorProdutosCTRC = @ValorProdutosCTRC,
   DataEntradaCTRC = @DataEntradaCTRC,
   DataEmissaoCTRC = @DataEmissaoCTRC,
   CaracteristicaTipoDocto = @CaracteristicaTipoDocto,
   CodigoTipoDocumento = @CodigoTipoDocumento,
   CodigoNaturezaOperacao = @CodigoNaturezaOperacao,
   CentroCusto = @CentroCusto,
   CodigoPlanoPagamento = @CodigoPlanoPagamento,
   ValorBaseICMSCTRC = @ValorBaseICMSCTRC,
   ValorBaseSubstTributaria = @ValorBaseSubstTributaria,
   ValorSubstTributaria = @ValorSubstTributaria,
   CodigoTipoPagamento = @CodigoTipoPagamento,
	MunicipioOrigem = @MunicipioOrigem,
	MunicipioDestino = @MunicipioDestino,
   CodigoTipoReceitaDespesa = @CodigoTipoReceitaDespesa
WHERE 
   CodigoEmpresa = @CodigoEmpresa AND
   CodigoLocal = @CodigoLocal AND
   CodigoCliForTransp = @CodigoCliForTransp AND
   NumeroCTRC = @NumeroCTRC
go
grant execute on dbo.spACTRCEntrada to SQLUsers
go
if object_id('spICTRC') is not null
	drop procedure dbo.spICTRC
go
CREATE PROCEDURE dbo.spICTRC
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliFor numeric(14) ,
   @NumeroConhecimento numeric(6) ,
   @DataEmissaoCTRCVeic datetime ,
   @DataVencimentoCTRC datetime = Null,
   @ValorCTRCEntradaVeic money ,
   @ValorICMSCTRCVeic money ,
   @QuantidadeVeiculos numeric(2) ,
   @DiferencaCTRC char(1) = 'F',
   @EspecieCTRCVeic char(3) ,
   @SerieCTRCVeic char(4) ,
   @RateadoCTRC char(1) = 'F',
   @CTRCAtualizadoContasPagar char(1) = 'F',
   @CTRCAtualizadoLivrosFiscais char(1) = 'F',
   @CTRCAtualizadoContabilidade char(1) = 'F',
   @DataEntradaCTRCVeic datetime ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CodigoTipoDocumento numeric(2) ,
   @CentroCusto numeric(8) ,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoPlanoPagamento char(4) = Null,
   @ValorBaseICMS money = 0,
   @PercICMS numeric(4,2) = 0,
   @ValorBaseSubstTributaria money = 0,
   @ValorSubstTributaria money = 0,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS 
INSERT tbCTRC (
   CodigoEmpresa,
   CodigoLocal,
   CodigoCliFor,
   NumeroConhecimento,
   DataEmissaoCTRCVeic,
   DataVencimentoCTRC,
   ValorCTRCEntradaVeic,
   ValorICMSCTRCVeic,
   QuantidadeVeiculos,
   DiferencaCTRC,
   EspecieCTRCVeic,
   SerieCTRCVeic,
   RateadoCTRC,
   CTRCAtualizadoContasPagar,
   CTRCAtualizadoLivrosFiscais,
   CTRCAtualizadoContabilidade,
   DataEntradaCTRCVeic,
   CodigoNaturezaOperacao,
   CodigoTipoDocumento,
   CentroCusto,
   CaracteristicaTipoDocto,
   CodigoPlanoPagamento,
   ValorBaseICMS,
   PercICMS,
   ValorBaseSubstTributaria,
   ValorSubstTributaria,
	MunicipioOrigem,
	MunicipioDestino,
   CodigoTipoReceitaDespesa
) VALUES (
   @CodigoEmpresa,
   @CodigoLocal,
   @CodigoCliFor,
   @NumeroConhecimento,
   @DataEmissaoCTRCVeic,
   @DataVencimentoCTRC,
   @ValorCTRCEntradaVeic,
   @ValorICMSCTRCVeic,
   @QuantidadeVeiculos,
   @DiferencaCTRC,
   @EspecieCTRCVeic,
   @SerieCTRCVeic,
   @RateadoCTRC,
   @CTRCAtualizadoContasPagar,
   @CTRCAtualizadoLivrosFiscais,
   @CTRCAtualizadoContabilidade,
   @DataEntradaCTRCVeic,
   @CodigoNaturezaOperacao,
   @CodigoTipoDocumento,
   @CentroCusto,
   @CaracteristicaTipoDocto,
   @CodigoPlanoPagamento,
   @ValorBaseICMS,
   @PercICMS,
   @ValorBaseSubstTributaria,
   @ValorSubstTributaria,
	@MunicipioOrigem,
	@MunicipioDestino,
   @CodigoTipoReceitaDespesa
   )
go
grant execute on dbo.spICTRC to SQLUsers
go
if object_id('spACTRC') is not null
	drop procedure dbo.spACTRC
go
CREATE PROCEDURE dbo.spACTRC
   @CodigoEmpresa numeric(4) ,
   @CodigoLocal numeric(4) ,
   @CodigoCliFor numeric(14) ,
   @NumeroConhecimento numeric(6) ,
   @DataEmissaoCTRCVeic datetime ,
   @DataVencimentoCTRC datetime = Null,
   @ValorCTRCEntradaVeic money ,
   @ValorICMSCTRCVeic money ,
   @QuantidadeVeiculos numeric(2) ,
   @DiferencaCTRC char(1) = 'F',
   @EspecieCTRCVeic char(3) ,
   @SerieCTRCVeic char(4) ,
   @RateadoCTRC char(1) = 'F',
   @CTRCAtualizadoContasPagar char(1) = 'F',
   @CTRCAtualizadoLivrosFiscais char(1) = 'F',
   @CTRCAtualizadoContabilidade char(1) = 'F',
   @DataEntradaCTRCVeic datetime ,
   @CodigoNaturezaOperacao numeric(6) ,
   @CodigoTipoDocumento numeric(2) ,
   @CentroCusto numeric(8) ,
   @CaracteristicaTipoDocto char(2) ,
   @CodigoPlanoPagamento char(4) = Null,
   @ValorBaseICMS money = 0,
   @PercICMS numeric(4,2) = 0,
   @ValorBaseSubstTributaria money = 0,
   @ValorSubstTributaria money = 0,
	@MunicipioOrigem varchar(8) = null,
	@MunicipioDestino varchar(8) = null,
   @CodigoTipoReceitaDespesa varchar(20) = null
AS 
UPDATE tbCTRC SET
   DataEmissaoCTRCVeic = @DataEmissaoCTRCVeic,
   DataVencimentoCTRC = @DataVencimentoCTRC,
   ValorCTRCEntradaVeic = @ValorCTRCEntradaVeic,
   ValorICMSCTRCVeic = @ValorICMSCTRCVeic,
   QuantidadeVeiculos = @QuantidadeVeiculos,
   DiferencaCTRC = @DiferencaCTRC,
   EspecieCTRCVeic = @EspecieCTRCVeic,
   SerieCTRCVeic = @SerieCTRCVeic,
   RateadoCTRC = @RateadoCTRC,
   CTRCAtualizadoContasPagar = @CTRCAtualizadoContasPagar,
   CTRCAtualizadoLivrosFiscais = @CTRCAtualizadoLivrosFiscais,
   CTRCAtualizadoContabilidade = @CTRCAtualizadoContabilidade,
   DataEntradaCTRCVeic = @DataEntradaCTRCVeic,
   CodigoNaturezaOperacao = @CodigoNaturezaOperacao,
   CodigoTipoDocumento = @CodigoTipoDocumento,
   CentroCusto = @CentroCusto,
   CaracteristicaTipoDocto = @CaracteristicaTipoDocto,
   CodigoPlanoPagamento = @CodigoPlanoPagamento,
   ValorBaseICMS = @ValorBaseICMS,
   PercICMS = @PercICMS,
   ValorBaseSubstTributaria = @ValorBaseSubstTributaria,
   ValorSubstTributaria = @ValorSubstTributaria,
	MunicipioOrigem = @MunicipioOrigem,
	MunicipioDestino = @MunicipioDestino,
   CodigoTipoReceitaDespesa = @CodigoTipoReceitaDespesa
WHERE 
   CodigoEmpresa = @CodigoEmpresa AND
   CodigoLocal = @CodigoLocal AND
   CodigoCliFor = @CodigoCliFor AND
   NumeroConhecimento = @NumeroConhecimento 
go
grant execute on dbo.spACTRC to SQLUsers
go
