SELECT * FROM tbDocumento WHERE NumeroDocumento = 14339 and DataDocumento = '2017-03-07'
--COLETAR O NUMERO DO PEDIDO NA TABELA DA TBDOCUMENTO.

SELECT * FROM tbPedido WHERE NumeroPedido = 210375   --((COLOCAR O NUMERO DO PEDIDO COLETADO DA TABELA TBDOCUMENTO.)) AND CENTROCUSTO = 
SELECT * FROM tbItemPedido WHERE NumeroPedido = 210375  --((COLOCAR O NUMERO DO PEDIDO COLETADO DA TABELA TBDOCUMENTO))  AND CENTROCUSTO = .