alter table tbPreOS add ContatoClientePreOS varchar(30)
go
DROP PROCEDURE dbo.spAPreOS 

GO

CREATE PROCEDURE dbo.spAPreOS   

 @CodigoEmpresa  numeric(4),  
 @CodigoLocal  numeric(4),  
 @NumeroPreOS  numeric(6),  
 @DataPreOS   datetime,  
 @CodConsultorPreOS  numeric(6),  
 @DataAgendamentoInicio datetime,  
 @DataAgendamentoFim  datetime,  
 @CodigoCliFor   numeric(14),  
 @ChassiVeiculoOS  char(30),  
 @SolicitanteParticular  char(1) = 'F',  
 @SolicitanteSeguradora  char(1) = 'F',  
 @DescricaoSeguradora    varchar(60),  
 @TipoServicoRevisao  char(1) = 'F',  
 @TipoServicoGarantia char(1) = 'F',  
 @TipoServicoRecall  char(1) = 'F',  
 @TipoServicoFunilaria char(1) = 'F',  
 @TipoServicoRetorno  char(1) = 'F',  
 @TipoServicoEmergencia char(1) = 'F',  
 @TipoServicoOutros  char(1) = 'F',  
 @DescricaoOutros  varchar(30),  
 @SintomasVeiculo  varchar(255),  
 @SituacaoSintoma  varchar(100),  
 @LocalSintoma   varchar(100),  
 @FrequenciaSintoma  varchar(100),  
 @HistoricoVeiculo  varchar(255),  
 @RecepcaoNormal   char(1) = 'F',  
 @RecHorarioEspecial  datetime,  
 @ServicoRecolha   char(1) = 'F',   
 @ServRecolhaEndereco    char(60),  
 @TranspAlterLocaVeiculo char(1) = 'F',  
 @TranspAlterLevaTraz char(1) = 'F',  
 @TranspAlterTaxi  char(1) = 'F',  
 @TranspAlterNaoSolicit  char(1) = 'F',  
 @PrevisaoEntrega  datetime,  
 @EntregaNormal      char(1) = 'F',  
 @EntHorarioEspecial     datetime,  
 @ServicoEntrega      char(1) = 'F',   
 @ServEntregaEndereco    char(60),  
 @InfAdicCusto   varchar(255),  
 @InfAdicPecas   varchar(255),  
 @InfAdicOutros      varchar(255),  
 @RespostaQuestao1  char(1) = 'F',  
 @MotivoQuestao1      varchar(60),  
 @RespostaQuestao2  char(1) = 'F',  
 @MotivoQuestao2      varchar(60),  
 @RespostaQuestao3  char(1) = 'F',  
 @MotivoQuestao3      varchar(60),  
 @RespostaQuestao4  char(1) = 'F',  
 @MotivoQuestao4      varchar(60),  
 @RespostaQuestao5  char(1) = 'F',  
 @MotivoQuestao5      varchar(60),  
 @RespostaQuestao6  char(1) = 'F',  
 @MotivoQuestao6      varchar(60),  
 @Questao6FichaManut     char(1) = 'F',  
 @Questao6RelTIPS  char(1) = 'F',  
 @Questao6IntroWIS  char(1) = 'F',  
 @Questao6OSPend      char(1) = 'F',  
 @RespostaQuestao7  char(1) = 'F',  
 @MotivoQuestao7      varchar(60),  
 @RespostaQuestao8  char(1) = 'F',  
 @MotivoQuestao8      varchar(60),  
 @RespostaQuestao9  char(1) = 'F',  
 @MotivoQuestao9      varchar(60),  
 @Observacoes   varchar(100),  
 @KmVeiculoOS   numeric(8),  
 @MotivoCancelamentoPreOS varchar(500),  
 @DataCancelamentoPreOS datetime = null,  
 @DataEntradaVeiculo  datetime = Null,  
 @DataInicioServico  datetime = Null,  
 @DataTerminoServico  datetime = NUll,
 @CreditoVerificado char(1),
 @BoxProvisorio dtInteiro03 = Null,
 @CITProvisorio char(4) = Null,
 @TipoPreOS char(2) = Null,
 @VeiculoEntregue char(1) = 'F',
 @TipoServicoMecanica char(1) = 'F',
 @TipoServicoEletrica char(1) = 'F',
 @TipoServicoDiagnostico char(1) = 'F',
 @TipoServicoTrocaOleoFiltro char(1) = 'F',
 @CheckListPreenchido char(1) = 'F',
 @ContatoClientePreOS varchar(30) = Null

AS UPDATE tbPreOS SET   
 DataPreOS    = @DataPreOS    ,   
 CodConsultorPreOS  = @CodConsultorPreOS  ,     
 DataAgendamentoInicio = @DataAgendamentoInicio ,    
 DataAgendamentoFim  = @DataAgendamentoFim  ,  
 CodigoCliFor   =  @CodigoCliFor   ,  
 ChassiVeiculoOS   =  @ChassiVeiculoOS  ,  
 SolicitanteParticular =  @SolicitanteParticular  ,    
 SolicitanteSeguradora   =  @SolicitanteSeguradora ,    
 DescricaoSeguradora  =  @DescricaoSeguradora    ,   
 TipoServicoRevisao  =  @TipoServicoRevisao  ,    
 TipoServicoGarantia  =  @TipoServicoGarantia ,    
 TipoServicoRecall  =  @TipoServicoRecall  ,    
 TipoServicoFunilaria =  @TipoServicoFunilaria ,    
 TipoServicoRetorno  =  @TipoServicoRetorno  ,    
 TipoServicoEmergencia =  @TipoServicoEmergencia ,    
 TipoServicoOutros  =  @TipoServicoOutros  ,    
 DescricaoOutros     =  @DescricaoOutros   ,  
 SintomasVeiculo     =  @SintomasVeiculo   ,     
 SituacaoSintoma     =  @SituacaoSintoma   ,  
 LocalSintoma     =  @LocalSintoma    ,  
 FrequenciaSintoma   =  @FrequenciaSintoma   ,  
 HistoricoVeiculo    =  @HistoricoVeiculo   ,  
 RecepcaoNormal     =  @RecepcaoNormal    ,  
 RecHorarioEspecial  =  @RecHorarioEspecial   ,  
 ServicoRecolha     =  @ServicoRecolha      ,   
 ServRecolhaEndereco =  @ServRecolhaEndereco  ,  
 TranspAlterLocaVeiculo  =  @TranspAlterLocaVeiculo ,    
 TranspAlterLevaTraz  =  @TranspAlterLevaTraz ,    
 TranspAlterTaxi   =  @TranspAlterTaxi  ,    
 TranspAlterNaoSolicit =  @TranspAlterNaoSolicit ,    
 PrevisaoEntrega   =  @PrevisaoEntrega  ,   
 EntregaNormal   =  @EntregaNormal      ,    
 EntHorarioEspecial  =  @EntHorarioEspecial     ,   
 ServicoEntrega   =  @ServicoEntrega      ,     
 ServEntregaEndereco  =  @ServEntregaEndereco    ,   
 InfAdicCusto  =  @InfAdicCusto    ,  
 InfAdicPecas  =  @InfAdicPecas    ,  
 InfAdicOutros  =  @InfAdicOutros    ,  
 RespostaQuestao1 =  @RespostaQuestao1   ,  
 MotivoQuestao1  =  @MotivoQuestao1    ,  
 RespostaQuestao2 =  @RespostaQuestao2   ,  
 MotivoQuestao2  =  @MotivoQuestao2    ,  
 RespostaQuestao3 =  @RespostaQuestao3   ,  
 MotivoQuestao3  =  @MotivoQuestao3    ,  
 RespostaQuestao4 =  @RespostaQuestao4   ,  
 MotivoQuestao4  =  @MotivoQuestao4    ,  
 RespostaQuestao5 =  @RespostaQuestao5   ,  
 MotivoQuestao5  =  @MotivoQuestao5    ,  
 RespostaQuestao6 =  @RespostaQuestao6   ,  
 MotivoQuestao6  =  @MotivoQuestao6    ,  
 Questao6FichaManut  =  @Questao6FichaManut   ,  
 Questao6RelTIPS     =  @Questao6RelTIPS   ,  
 Questao6IntroWIS    =  @Questao6IntroWIS   ,  
 Questao6OSPend      =  @Questao6OSPend    ,  
 RespostaQuestao7    =  @RespostaQuestao7   ,  
 MotivoQuestao7      =  @MotivoQuestao7    ,  
 RespostaQuestao8    =  @RespostaQuestao8   ,  
 MotivoQuestao8      =  @MotivoQuestao8    ,  
 RespostaQuestao9    =  @RespostaQuestao9   ,  
 MotivoQuestao9      =  @MotivoQuestao9    ,  
 Observacoes         =  @Observacoes    ,  
 KmVeiculoOS   =   @KmVeiculoOS    ,  
 MotivoCancelamentoPreOS = @MotivoCancelamentoPreOS ,  
 DataCancelamentoPreOS = @DataCancelamentoPreOS,  
 DataEntradaVeiculo = case when convert(char(10), @DataEntradaVeiculo,120) = '1900-01-01'
						  then null
						  else @DataEntradaVeiculo
						  end ,  
 DataInicioServico =  case when convert(char(10), @DataInicioServico,120) = '1900-01-01'
						  then null
						  else @DataInicioServico
						  end ,  
 DataTerminoServico = case when convert(char(10), @DataTerminoServico,120) = '1900-01-01'
						  then null
						  else @DataTerminoServico
						  end ,
 CreditoVerificado = @CreditoVerificado,
 BoxProvisorio = @BoxProvisorio,
 CITProvisorio = @CITProvisorio,
 TipoPreOS = @TipoPreOS,
 VeiculoEntregue = @VeiculoEntregue,
 TipoServicoMecanica = @TipoServicoMecanica,
 TipoServicoEletrica = @TipoServicoEletrica,
 TipoServicoDiagnostico = @TipoServicoDiagnostico,
 TipoServicoTrocaOleoFiltro = @TipoServicoTrocaOleoFiltro,
 CheckListPreenchido = @CheckListPreenchido,
 ContatoClientePreOS = @ContatoClientePreOS
WHERE   
    CodigoEmpresa = @CodigoEmpresa  AND  
    CodigoLocal   = @CodigoLocal AND  
    NumeroPreOS   = @NumeroPreOS
go

DROP PROCEDURE dbo.spIPreOS  

GO
CREATE PROCEDURE dbo.spIPreOS  
 @CodigoEmpresa  numeric(4),  
 @CodigoLocal  numeric(4),  
 @NumeroPreOS  numeric(6),  
 @DataPreOS   datetime,  
 @CodConsultorPreOS  numeric(6),  
 @DataAgendamentoInicio datetime,  
 @DataAgendamentoFim  datetime,  
 @CodigoCliFor   numeric(14),  
 @ChassiVeiculoOS  char(30),  
 @SolicitanteParticular  char(1) = 'F',  
 @SolicitanteSeguradora  char(1) = 'F',  
 @DescricaoSeguradora    varchar(60),  
 @TipoServicoRevisao  char(1) = 'F',  
 @TipoServicoGarantia char(1) = 'F',  
 @TipoServicoRecall  char(1) = 'F',  
 @TipoServicoFunilaria char(1) = 'F',  
 @TipoServicoRetorno  char(1) = 'F',  
 @TipoServicoEmergencia char(1) = 'F',  
 @TipoServicoOutros  char(1) = 'F',  
 @DescricaoOutros  varchar(30),  
 @SintomasVeiculo  varchar(255),  
 @SituacaoSintoma  varchar(100),  
 @LocalSintoma   varchar(100),  
 @FrequenciaSintoma  varchar(100),  
 @HistoricoVeiculo  varchar(255),  
 @RecepcaoNormal   char(1) = 'F',  
 @RecHorarioEspecial  datetime,  
 @ServicoRecolha   char(1) = 'F',   
 @ServRecolhaEndereco    char(60),  
 @TranspAlterLocaVeiculo char(1) = 'F',  
 @TranspAlterLevaTraz char(1) = 'F',  
 @TranspAlterTaxi  char(1) = 'F',  
 @TranspAlterNaoSolicit  char(1) = 'F',  
 @PrevisaoEntrega  datetime,  
 @EntregaNormal      char(1) = 'F',  
 @EntHorarioEspecial     datetime,  
 @ServicoEntrega      char(1) = 'F',   
 @ServEntregaEndereco    char(60),  
 @InfAdicCusto   varchar(255),  
 @InfAdicPecas   varchar(255),  
 @InfAdicOutros      varchar(255),  
 @RespostaQuestao1  char(1) = 'F',  
 @MotivoQuestao1      varchar(60),  
 @RespostaQuestao2  char(1) = 'F',  
 @MotivoQuestao2      varchar(60),  
 @RespostaQuestao3  char(1) = 'F',  
 @MotivoQuestao3      varchar(60),  
 @RespostaQuestao4  char(1) = 'F',  
 @MotivoQuestao4      varchar(60),  
 @RespostaQuestao5  char(1) = 'F',  
 @MotivoQuestao5      varchar(60),  
 @RespostaQuestao6  char(1) = 'F',  
 @MotivoQuestao6      varchar(60),  
 @Questao6FichaManut     char(1) = 'F',  
 @Questao6RelTIPS  char(1) = 'F',  
 @Questao6IntroWIS  char(1) = 'F',  
 @Questao6OSPend      char(1) = 'F',  
 @RespostaQuestao7  char(1) = 'F',  
 @MotivoQuestao7      varchar(60),  
 @RespostaQuestao8  char(1) = 'F',  
 @MotivoQuestao8      varchar(60),  
 @RespostaQuestao9  char(1) = 'F',  
 @MotivoQuestao9      varchar(60),  
 @Observacoes   varchar(100),  
 @KmVeiculoOS   numeric(8),  
 @MotivoCancelamentoPreOS varchar(500),  
 @DataCancelamentoPreOS datetime = null,  
 @DataEntradaVeiculo  datetime = Null,  
 @DataInicioServico  datetime = Null,  
 @DataTerminoServico  datetime = Null,
 @CreditoVerificado	char(1),
 @BoxProvisorio dtInteiro03 = Null,
 @CITProvisorio char(4) = Null,
 @TipoPreOS char(2) = Null,
 @VeiculoEntregue char(1) = 'F',
 @TipoServicoMecanica char(1) = 'F',
 @TipoServicoEletrica char(1) = 'F',
 @TipoServicoDiagnostico char(1) = 'F',
 @TipoServicoTrocaOleoFiltro char(1) = 'F',
 @CheckListPreenchido char(1) = 'F',
 @ContatoClientePreOS varchar(30) = Null

AS INSERT tbPreOS   
(  
 CodigoEmpresa ,  
 CodigoLocal  ,  
 NumeroPreOS  ,  
 DataPreOS  ,  
 CodConsultorPreOS  ,  
 DataAgendamentoInicio ,  
 DataAgendamentoFim  ,  
 CodigoCliFor   ,  
 ChassiVeiculoOS   ,  
 SolicitanteParticular ,  
 SolicitanteSeguradora ,  
 DescricaoSeguradora  ,  
 TipoServicoRevisao  ,  
 TipoServicoGarantia  ,  
 TipoServicoRecall  ,  
 TipoServicoFunilaria ,  
 TipoServicoRetorno  ,  
 TipoServicoEmergencia ,  
 TipoServicoOutros  ,  
 DescricaoOutros   ,  
 SintomasVeiculo   ,  
 SituacaoSintoma   ,  
 LocalSintoma   ,  
 FrequenciaSintoma  ,  
 HistoricoVeiculo  ,  
 RecepcaoNormal   ,  
 RecHorarioEspecial  ,  
 ServicoRecolha   ,    
 ServRecolhaEndereco  ,  
 TranspAlterLocaVeiculo  ,  
 TranspAlterLevaTraz  ,  
 TranspAlterTaxi   ,  
 TranspAlterNaoSolicit   ,  
 PrevisaoEntrega   ,   
 EntregaNormal   ,  
 EntHorarioEspecial  ,  
 ServicoEntrega   ,   
 ServEntregaEndereco  ,  
 InfAdicCusto   ,  
 InfAdicPecas   ,  
 InfAdicOutros   ,  
 RespostaQuestao1  ,  
 MotivoQuestao1   ,  
 RespostaQuestao2  ,  
 MotivoQuestao2   ,  
 RespostaQuestao3  ,  
 MotivoQuestao3   ,  
 RespostaQuestao4  ,  
 MotivoQuestao4   ,  
 RespostaQuestao5  ,  
 MotivoQuestao5   ,  
 RespostaQuestao6  ,  
 MotivoQuestao6   ,  
 Questao6FichaManut  ,  
 Questao6RelTIPS   ,  
 Questao6IntroWIS  ,  
 Questao6OSPend   ,  
 RespostaQuestao7  ,  
 MotivoQuestao7   ,  
 RespostaQuestao8  ,  
 MotivoQuestao8   ,  
 RespostaQuestao9  ,  
 MotivoQuestao9   ,  
 Observacoes    ,  
 KmVeiculoOS    ,  
 MotivoCancelamentoPreOS ,  
 DataCancelamentoPreOS ,  
 DataEntradaVeiculo  ,  
 DataInicioServico  ,  
 DataTerminoServico,
 CreditoVerificado,
 BoxProvisorio,
 CITProvisorio,
 TipoPreOS,
 VeiculoEntregue,
 TipoServicoMecanica,
 TipoServicoEletrica,
 TipoServicoDiagnostico,
 TipoServicoTrocaOleoFiltro,
 CheckListPreenchido,
 ContatoClientePreOS
)  
  
VALUES   
(  
 @CodigoEmpresa    ,  
 @CodigoLocal   ,  
 @NumeroPreOS   ,  
 @DataPreOS    ,  
 @CodConsultorPreOS    ,  
 @DataAgendamentoInicio    ,  
 @DataAgendamentoFim    ,  
 @CodigoCliFor     ,  
 @ChassiVeiculoOS    ,  
 @SolicitanteParticular    ,  
 @SolicitanteSeguradora    ,  
 @DescricaoSeguradora      ,  
 @TipoServicoRevisao    ,  
 @TipoServicoGarantia   ,  
 @TipoServicoRecall    ,  
 @TipoServicoFunilaria   ,  
 @TipoServicoRetorno    ,  
 @TipoServicoEmergencia   ,  
 @TipoServicoOutros    ,  
 @DescricaoOutros    ,  
 @SintomasVeiculo    ,  
 @SituacaoSintoma    ,  
 @LocalSintoma     ,  
 @FrequenciaSintoma    ,  
 @HistoricoVeiculo    ,  
 @RecepcaoNormal     ,  
 @RecHorarioEspecial    ,  
 @ServicoRecolha     ,   
 @ServRecolhaEndereco      ,  
 @TranspAlterLocaVeiculo   ,  
 @TranspAlterLevaTraz   ,  
 @TranspAlterTaxi    ,  
 @TranspAlterNaoSolicit    ,  
 @PrevisaoEntrega    ,  
 @EntregaNormal        ,  
 @EntHorarioEspecial       ,  
 @ServicoEntrega        ,   
 @ServEntregaEndereco      ,  
 @InfAdicCusto     ,  
 @InfAdicPecas     ,  
 @InfAdicOutros        ,  
 @RespostaQuestao1    ,  
 @MotivoQuestao1        ,  
 @RespostaQuestao2    ,  
 @MotivoQuestao2        ,  
 @RespostaQuestao3    ,  
 @MotivoQuestao3        ,  
 @RespostaQuestao4    ,  
 @MotivoQuestao4        ,  
 @RespostaQuestao5    ,  
 @MotivoQuestao5        ,  
 @RespostaQuestao6    ,  
 @MotivoQuestao6        ,  
 @Questao6FichaManut       ,  
 @Questao6RelTIPS    ,  
 @Questao6IntroWIS    ,  
 @Questao6OSPend        ,  
 @RespostaQuestao7    ,  
 @MotivoQuestao7        ,  
 @RespostaQuestao8    ,  
 @MotivoQuestao8        ,  
 @RespostaQuestao9    ,  
 @MotivoQuestao9        ,  
 @Observacoes     ,  
 @KmVeiculoOS     ,  
 @MotivoCancelamentoPreOS ,  
 @DataCancelamentoPreOS ,  
 case when convert(char(10), @DataEntradaVeiculo,120) = '1900-01-01'
	  then null
	  else @DataEntradaVeiculo
	  end  ,  
 case when convert(char(10), @DataInicioServico,120) = '1900-01-01'
	  then null
	  else @DataInicioServico
	  end  ,  
 case when convert(char(10), @DataTerminoServico,120) = '1900-01-01'
	  then null
	  else @DataTerminoServico
	  end  ,  
 @CreditoVerificado,
 @BoxProvisorio,
 @CITProvisorio,
 @TipoPreOS,
 @VeiculoEntregue,
 @TipoServicoMecanica,
 @TipoServicoEletrica,
 @TipoServicoDiagnostico,
 @TipoServicoTrocaOleoFiltro,
 @CheckListPreenchido,
 @ContatoClientePreOS
)